# Generated by Django 6.0.7 on 2026-07-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('min_gwa_percent', models.FloatField(blank=True, null=True)),
                ('max_family_income', models.FloatField(blank=True, null=True)),
                ('year_levels', models.JSONField(blank=True, default=list)),
                ('course_keywords', models.JSONField(blank=True, default=list)),
                ('region', models.CharField(default='any', max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('link', models.URLField(unique=True)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('last_scraped_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
